### ISSUE TITLE
Rewrite apps installation script as an Ansible playbook

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/devspace#5]
1.
```console
pip install ansible-core --user
```
2. create an inventory file with a `localhost` entry in it with `connection=local` param
3. create a playbook `install-apps.yml`
it'd look smth like
```yaml
- name: Install OS-level apps
  hosts: all
  become: yes
  tasks:
  - name: Configure repositories
    apt_repository:
      ...
  - name: Install apps
    apt:
      name:
      - 
      - 
      ...
```
4. The invocation would look like:
```console
ansible-playbook -i inventory -K install-apps.yml
```

Ref: https://docs.ansible.com/ansible/devel/user_guide/index.html
Ref: https://docs.ansible.com/ansible/devel/modules/apt_module.html
Ref: https://docs.ansible.com/ansible/devel/modules/apt_repository_module.html
